### ISSUE TITLE
Socials, Net question

### ISSUE THREAD

**Issue by MidasMining** [AnonimityCash/BTCturquoise-v2.0.54.3#1]
Hi,

Is this testnet or mainnet? Do you have any socials established for this project?

**Comment by AnonimityCash** [comment]
This is already the mainnet network, perhaps in the near future if we had to modify something on the main chain it would always be previously a consensus of the BTCtuquoise Community, there is nothing here, nor will there be anything imposed. Regarding social networks, you can follow us for now and get quick information here: https://twitter.com/btcturquoise
 but soon we will have all common social networks available. For now we only work on different parts of the project.
