### ISSUE TITLE
btcturquoise-qt.exe

### ISSUE THREAD

**Issue by Liujiarong123** [AnonimityCash/BTCturquoise-v2.0.54.3#2]
Incorrect or no genesis block found. Wrong datadir for
network?

**Comment by AnonimityCash** [comment]
We are reviewing it and on our side everything works correctly and the wallet is synchronized and connected to its corresponding nodes with the correct block height. Please check on your side, we will still compile a new version and upload it, in case there are unexpected errors.

**Comment by AnonimityCash** [comment]
Could you please check it now if it works correctly? Compile your BTCturquoise-qt.exe again, it should work fine. If not, please let us know so we can continue searching for the problem/error.
