### ISSUE TITLE
hard to connect

### ISSUE THREAD

**Issue by zanzhz1101** [AnonimityCash/BTCturquoise-v2.0.54.3#3]
hard to connect basic nodes,could BTCQ update more nodes please？

**Comment by AnonimityCash** [comment]
addnode=84.42.23.120:3333
addnode=141.94.192.217:3333
addnode=103.166.184.51:3333
addnode=51.222.240.201:3333
addnode=1.52.153.155:3333
addnode=15.235.212.162:3333

**Comment by AnonimityCash** [comment]
In the configuration section, in the "NETWORK" section activate "port mapping using UPnP" you will have better connections with nodes and fast synchronization
