### ISSUE TITLE
Hive not connecting

### ISSUE THREAD

**Issue by scubari** [AnonimityCash/BTCturquoise-v2.0.54.3#4]
Im mining this with win pc and few rigs with hive os. Win+wildrig works fine but with HIVE cant connect to any given stratum/url. xmrig is acting up in hive too even it works great with win. thanks

![2024-01-10 194904](https://github.com/AnonimityCash/BTCturquoise-v2.0.54.3/assets/17438389/912916d2-3498-4077-9129-5693d61b87a1)

**Comment by AnonimityCash** [comment]
I'm sorry for the delay in answering your message, did you finally manage to solve it?
