### ISSUE TITLE
Executable file format error.

### ISSUE THREAD

**Issue by yoyofreeman** [AnonimityCash/BTCturquoise-v2.0.54.3#6]
![选区_121](https://github.com/AnonimityCash/BTCturquoise-v2.0.54.3/assets/35377453/a68efec5-afc9-444d-b672-5b5f5863376e)

**Comment by AnonimityCash** [comment]
Permissions use , sudo chmod 777 -R * 
you have to make it executable

**Comment by AnonimityCash** [comment]
This version is new and should work.
https://github.com/AnonimityCash/BTCturquoise-v2.0.54.3/releases/download/v2.0.54.3/x86_64-pc-linux-gnu.tar.gz
