### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by adlinkflyy** [AnonimityCash/BTCturquoise-v2.0.54.3#7]
![Screenshot_20240301-194434_Termius](https://github.com/AnonimityCash/BTCturquoise-v2.0.54.3/assets/129060358/fa007215-2548-4deb-8e00-1affac9130e0)

**Comment by adlinkflyy** [comment]
![Screenshot_20240301-194831_Termius](https://github.com/AnonimityCash/BTCturquoise-v2.0.54.3/assets/129060358/a555ebd5-30fa-4210-bcc2-d3bfcc61b154)

**Comment by AnonimityCash** [comment]
This version is new and should work
https://github.com/AnonimityCash/BTCturquoise-v2.0.54.3/releases/download/v2.0.54.3/x86_64-pc-linux-gnu.tar.gz
